server:
  port: 9223
  undertow:
    buffer-size: 1024
    direct-buffers: true
#  servlet:
#    context-path: /adminService
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://rm-bp1l9tml81r1i5i18xo.mysql.rds.aliyuncs.com:3306/sys_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: sys_admin_user
    password: admin852!
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置Druid的其他参数，以下配置必须增加一个配置文件才能有效
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 获取连接等待超时的时间
    maxWait: 300000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall
    # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 文件上传相关参数
  servlet:
    multipart:
      max-file-size: 10MB # 设置单个文件的大小为10M
      max-request-size: 50MB # 设置总上传的数据大小为50M
    file-win-path: D:/admin-service/files/
    file-linux-path: /home/files/

